def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add the email column with a temporary default value to satisfy the NOT NULL constraint
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False, server_default='temp@example.com'))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # After adding the column with the temporary default, you might want to update the column to remove the server_default if it's not needed
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(), nullable=False, server_default=None)
    # ### end Alembic commands ###