"""empty message

Revision ID: 6b058642f578
Revises: ebf8a9fab544
Create Date: 2024-03-18 07:16:03.003623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b058642f578'
down_revision = 'ebf8a9fab544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add the email column with a temporary default value to satisfy the NOT NULL constraint
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False, server_default='temp@example.com'))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # After adding the column with the temporary default, you might want to update the column to remove the server_default if it's not needed
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(), nullable=False, server_default=None)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
